apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-depolyment
  namespace: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: lalll5555/apache:latest
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: apache
  type: LoadBalancer
  loadBalancerIP: 203.235.116.240

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
  - hosts:
    - leesb.inet.co.kr
    secretName: quickstart-example-tls
  rules:
    - host: leesb.inet.co.kr
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apache-service
              port:
                number: 80
