apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-depolyment
  namespace: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: lalll5555/apache:${env.BUILD_NUMBER}
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: apache
